# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        my_config:
            language: fr
            uiColor: "#28AD7A"
            lineHeight: 1px
            toolbar: [
                [ 'Bold', 'Italic', 'Underline', 'TextColor', '-',  'RemoveFormat' ],
                [ 'NumberedList', 'BulletedList', 'Blockquote', ],
                [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', ]
            ]
